[package]
name = "prospero"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Stepan Kizim <stsiapan.kizim@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
serenity = { version = "0.11", default-features = false, features = [
  "cache", "standard_framework", "voice", "rustls_backend"
] }
# symphonia = { features = ["aac", "mp3", "isomp4", "alac"], version = "0.5.2" }
songbird = "0.3"
tokio = { version = "1", features = ["rt-multi-thread"] }
